### ISSUE TITLE
Source files no longer available

### ISSUE THREAD

**Issue by rzsn** [online-stuff/tilera-toolchain#1]
None of the referenced source files to download from https://link.storjshare.io are available as of now:

> Resolving link.storjshare.io (link.storjshare.io)... 185.244.226.2
> Connecting to link.storjshare.io (link.storjshare.io)|185.244.226.2|:443... connected.
> HTTP request sent, awaiting response... 403 Forbidden
> 2024-10-14 11:58:38 ERROR 403: Forbidden.

Does this helper tool use some specially patched versions?

Could we just grab those exact versions from other GIT repos ?

**Comment by firstkevinds** [comment]
They were the unedited original files from before the company was sold many times..  I will try and find a new host for the files as they are too big to upload here.  If you find other sources (I left the original filenames) they should be the same.

Thanks for letting me know.  I'll leave this open until I find a new host.

**Comment by firstkevinds** [comment]
Moved to a different CDN.
